import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  Button,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NextUIProvider,
} from "@nextui-org/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <NextUIProvider>
            <Navbar>
              <NavbarBrand>
                <p className="font-bold">Matheus</p>
              </NavbarBrand>
              <NavbarContent className="sm:flex gap-4" justify="center">
                <NavbarItem isActive>
                  <Link color="foreground" href="#">
                    About
                  </Link>
                </NavbarItem>
                <NavbarItem>
                  <Link href="#" aria-current="page">
                    Projects
                  </Link>
                </NavbarItem>
                <NavbarItem>
                  <Link color="foreground" href="#">
                    Contacts
                  </Link>
                </NavbarItem>
              </NavbarContent>
            </Navbar>
            {children}
          </NextUIProvider>
        }
      </body>
    </html>
  );
}
